modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://luxmiyu.com/adm2-luxore/issues"
license = "MIT"

[[mods]]
modId = "adm2_luxore"
version = "${version}"
displayName = "Any Dimension Mod 2 - Luxore"
authors = "luxmiyu"
description = '''
Adds dimensions for Any Dimension Mod 2 using blocks from Luxore.
'''
logoFile = "icon.png"

[[dependencies.adm2_luxore]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adm2_luxore]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adm2_luxore]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

#[[mixins]]
#config = "adm2_luxore.mixins.json"
